# Generated by Django 5.2.4 on 2025-08-06 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='documentos.acta'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gestion',
            name='compromiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='documentos.compromiso'),
        ),
    ]
